import { AnimationStyle, Elevation, ElevationStyle, Palette } from "@apptane/react-ui-core";
import { AvatarTheme } from "./components/AvatarTheme.types";
import { BackdropTheme } from "./components/BackdropTheme.types";
import { BadgeTheme } from "./components/BadgeTheme.types";
import { BannerTheme } from "./components/BannerTheme.types";
import { BulletTheme } from "./components/BulletTheme.types";
import { ButtonTheme } from "./components/ButtonTheme.types";
import { CalendarTheme } from "./components/CalendarTheme.types";
import { ChartGaugeTheme } from "./components/ChartGaugeTheme.types";
import { ChartHexBinTheme } from "./components/ChartHexBinTheme.types";
import { ChartPieTheme } from "./components/ChartPieTheme.types";
import { ChartXYTheme } from "./components/ChartXYTheme.types";
import { DialogTheme } from "./components/DialogTheme.types";
import { DividerTheme } from "./components/DividerTheme.types";
import { DropdownTheme } from "./components/DropdownTheme.types";
import { FieldLabelTheme } from "./components/FieldLabelTheme.types";
import { FormTheme } from "./components/FormTheme.types";
import { HyperlinkTheme } from "./components/HyperlinkTheme.types";
import { InputBoxTheme } from "./components/InputBoxTheme.types";
import { InputCheckTheme } from "./components/InputCheckTheme.types";
import { InputSliderTheme } from "./components/InputSliderTheme.types";
import { InputToggleTheme } from "./components/InputToggleTheme.types";
import { MenuTheme } from "./components/MenuTheme.types";
import { PaneTheme } from "./components/PaneTheme.types";
import { ProgressTheme } from "./components/ProgressTheme.types";
import { RadioButtonTheme } from "./components/RadioButtonTheme.types";
import { ScrollerTheme } from "./components/ScrollerTheme.types";
import { SideBarTheme } from "./components/SideBarTheme.types";
import { SidePanelTheme } from "./components/SidePanelTheme.types";
import { SkeletonTheme } from "./components/SkeletonTheme.types";
import { TableViewTheme } from "./components/TableViewTheme.types";
import { TabsTheme } from "./components/TabsTheme.types";
import { TagTheme } from "./components/TagTheme.types";
import { ToastTheme } from "./components/ToastTheme.types";
import { TooltipTheme } from "./components/TooltipTheme.types";
import { Typography } from "./Typography.types";
import { ZIndex } from "./ZIndex.types";

export interface Theme {
  palette: {
    light: Palette;
    dark: Palette;
  };
  typography: Typography;
  zindex: ZIndex;
  animation: AnimationStyle;
  elevation: (level?: Elevation) => ElevationStyle | undefined;
  backdrop: BackdropTheme;
  components: {
    avatar: AvatarTheme;
    badge: BadgeTheme;
    banner: BannerTheme;
    bullet: BulletTheme;
    button: ButtonTheme;
    calendar: CalendarTheme;
    dialog: DialogTheme;
    divider: DividerTheme;
    dropdown: DropdownTheme;
    fieldLabel: FieldLabelTheme;
    form: FormTheme;
    hyperlink: HyperlinkTheme;
    inputBox: InputBoxTheme;
    inputCheck: InputCheckTheme;
    inputSlider: InputSliderTheme;
    inputToggle: InputToggleTheme;
    menu: MenuTheme;
    pane: PaneTheme;
    progress: ProgressTheme;
    radioButton: RadioButtonTheme;
    scroller: ScrollerTheme;
    sideBar: SideBarTheme;
    sidePanel: SidePanelTheme;
    skeleton: SkeletonTheme;
    tableView: TableViewTheme;
    tabs: TabsTheme;
    tag: TagTheme;
    toast: ToastTheme;
    tooltip: TooltipTheme;
  };
  charts: {
    gauge: ChartGaugeTheme;
    hexbin: ChartHexBinTheme;
    xy: ChartXYTheme;
    pie: ChartPieTheme;
  };
}
